#!/usr/bin/env ruby

formula_bundles = [ 
  "git clone git://github.com/scrooloose/nerdtree.git",
  "git clone git://github.com/tpope/vim-fugitive.git",
  "git clone https://github.com/scrooloose/syntastic.git",
#  "git clone git@github.com:mhinz/vim-startify.git",
  "git clone git@github.com:Valloric/YouCompleteMe.git && cd YouCompleteMe && git submodule update --init --recursive && ./install.py",
  "git clone https://github.com/Yggdroot/indentLine",
#  "git clone git://github.com/tpope/vim-surround.git",
  "git clone https://github.com/vim-airline/vim-airline",
  "git clone https://github.com/mattn/emmet-vim.git",
  "git clone https://github.com/leafgarland/typescript-vim.git",
  "git clone https://github.com/kien/ctrlp.vim",
  #"git clone https://github.com/Quramy/tsuquyomi.git",
  "git clone https://github.com/Shougo/vimproc.vim.git && cd ~/.vim/bundle/vimproc.vim && make",
  "git clone https://github.com/pangloss/vim-javascript.git",
  "git clone https://github.com/SirVer/ultisnips",
  "git clone https://github.com/fatih/vim-go.git",
  "git clone https://github.com/easymotion/vim-easymotion",
  "git clone https://github.com/captbaritone/better-indent-support-for-php-with-html.git",
  "git clone https://github.com/mxw/vim-jsx.git",
]

vim_org_scripts = [
 # ["matchit", "39", "utility"]
 # ["IndexedSearch", "7062",  "plugin"],
 # ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.expand_path(File.join(File.dirname(__FILE__), "bundle"))

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

formula_bundles.each do |formula|
  `cd #{bundles_dir}`
  puts "brewing #{formula}"
  `#{formula}`
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
